---
- name: add tor-project repository
  apt_repository:
    repo: deb https://deb.torproject.org/torproject.org xenial main
    filename: tor-project
    mode: 0644
  become: yes
  register: tor_repo_result

- name: install tor package from torproject.org
  apt:
    name:
      - tor
      - deb.torproject.org-keyring
    state: present
    update_cache: "{{ tor_repo_result is changed }}"
    allow_unauthenticated: yes
  become: yes
...
