---
- name: install tor
  include_tasks: "install-{{ ansible_lsb.codename }}.yml"
  args:
    apply:
      become: yes
      tags: lin_tor_install
  tags: lin_tor_install

- name: activate tor service
  systemd:
    name: tor
    state: started
    enabled: yes
  become: yes
  tags: lin_tor_service

- name: configure tor
  import_tasks: config.yml
  become: yes
  tags: lin_tor_config

- name: setup privoxy
  when: tor_privoxy_enable | bool
  import_tasks: privoxy.yml
  become: yes
  tags: lin_tor_privoxy

- meta: flush_handlers
...
