---
# handlers for ivansible.lin_tor

- name: restart tor service
  systemd:
    name: tor
    state: restarted
  become: true

- name: restart privoxy service
  systemd:
    name: privoxy
    state: restarted
  become: true
...
