---
# handlers file for ivansible.lin-tor

- name: restart tor service
  systemd:
    name: tor
    state: restarted
  become: yes

- name: restart privoxy service
  systemd:
    name: privoxy
    state: restarted
  become: yes
...
